name: 'monitoring'

on:
  workflow_dispatch:
  schedule: # hourly
    - cron: 0 * * * *

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  monitoring_matrix:
    strategy:
      matrix:
        flavor: [ 
          {env: preview, url: dev.race-dui.pages.dev} , 
          {env: production, url: race-dui.pages.dev}
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: monitoring
        run: scripts/test.sh monitoring ${{matrix.flavor.env}} ${{matrix.flavor.url}} monitoring
